server:
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
      max-threads: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare-threads: 30

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.bishe.netdisc.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapping/*Mapping.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.230.10:3306/scheduler?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: scheduler
    password: scheduler@123456

  data:
    mongodb:
      database: webdisk
      host: localhost
      port: 27017
  # 配置上传文件的最大值和上传最大值，单位MB或KB
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB

hdfs:
  path: hdfs://192.168.88.130:9000
#  全分布地址
#  path: hdfs://192.168.88.132:9000
  user: hadoop3